# Dockerfile.scheduler

FROM python:3.9-slim

WORKDIR /app

# Copy the requirements file first to leverage Docker cache
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY sources/scheduler.py .
COPY digital_twin_model.h5 .
COPY scaler.joblib .

# Run the scheduler app
CMD ["python", "-u", "scheduler.py"]